import type { UserSettings } from '../types/settings.types';

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'system',
  codeFontSize: 'medium',
  compactMode: false,
  reducedMotion: false,
  preferredLanguage: 'TypeScript',
  defaultDifficultyFilter: 'all',
  showLineNumbers: true,
  wordWrap: true,
  autoSyncDefault: true,
  defaultFolderStrategy: 'platform',
  generateReadmeDefault: true,
  includeMetadataDefault: true,
  commitMessageTemplate: 'feat: solve {problem}',
  defaultAIMode: 'General',
  aiResponseStyle: 'balanced',
  aiExplanationLevel: 'intermediate',
  includeCodeExamples: true,
  includeComplexityAnalysis: true,
  usePersonalContext: true,
  notifications: {
    syncSuccess: true,
    syncFailure: true,
    aiResponseReady: true,
    revisionReminder: true,
    achievementUnlocked: true,
    weeklyProgress: true,
    productUpdates: false,
  },
  privacy: {
    profileVisibility: 'public',
    showStats: true,
    showAchievements: true,
    showLanguages: true,
    showActivity: true,
    allowPersonalizedAI: true,
  },
};
